title: IA e-portfolio
description: A showcase of my learning outcomes for the IA module.
theme: just-the-docs

url: https://eportfolio-ia.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
